version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Packaging lambda..."
  post_build:
    commands:
      - echo "Build Completed"

      
